/*
 This file is part of Darling.

 Copyright (C) 2025 Darling Developers

 Darling is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Darling is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Darling.  If not, see <http://www.gnu.org/licenses/>.
*/


#ifndef _GameplayKit_H_
#define _GameplayKit_H_

#import <Foundation/Foundation.h>

#import <GameplayKit/GKAgentDelegate.h>
#import <GameplayKit/GKNoiseModule.h>
#import <GameplayKit/GKRandom.h>
#import <GameplayKit/GKSerializedNodeContaining.h>
#import <GameplayKit/GKStrategist.h>
#import <GameplayKit/NSKeyedUnarchiverDelegate.h>
#import <GameplayKit/GKRTree.h>
#import <GameplayKit/GKSKNodeComponent.h>
#import <GameplayKit/GKARC4RandomSource.h>
#import <GameplayKit/GKRandomDistribution.h>
#import <GameplayKit/GKGaussianDistribution.h>
#import <GameplayKit/GKShuffledDistribution.h>
#import <GameplayKit/GKCylindersNoiseSource.h>
#import <GameplayKit/GKNoiseMap.h>
#import <GameplayKit/GKMeshGraph.h>
#import <GameplayKit/GKMinmaxStrategist.h>
#import <GameplayKit/GKLinearCongruentialRandomSource.h>
#import <GameplayKit/GKMonteCarloStrategist.h>
#import <GameplayKit/GKEntity.h>
#import <GameplayKit/GKCheckerboardNoiseSource.h>
#import <GameplayKit/GKObstacle.h>
#import <GameplayKit/GKCircleObstacle.h>
#import <GameplayKit/GKPolygonObstacle.h>
#import <GameplayKit/GKSphereObstacle.h>
#import <GameplayKit/GKSystemArc4RandomSource.h>
#import <GameplayKit/GKRandomSource.h>
#import <GameplayKit/GKBillowNoiseSource.h>
#import <GameplayKit/GKDecisionNode.h>
#import <GameplayKit/GKDecisionTree.h>
#import <GameplayKit/GKAgent.h>
#import <GameplayKit/GKAgent2D.h>
#import <GameplayKit/GKAgent3D.h>
#import <GameplayKit/GKHybridStrategist.h>
#import <GameplayKit/GKRuleSystem.h>
#import <GameplayKit/_GKBlockRule.h>
#import <GameplayKit/GKRule.h>
#import <GameplayKit/_GKNSBoolPredicateTemplate.h>
#import <GameplayKit/_GKNSKeypathPredicateTemplate.h>
#import <GameplayKit/GKNSPredicateRule.h>
#import <GameplayKit/_GKNSPredicateRule.h>
#import <GameplayKit/GKGraph.h>
#import <GameplayKit/GKRidgedNoiseSource.h>
#import <GameplayKit/GKQuadtreeNode.h>
#import <GameplayKit/GKQuadtree.h>
#import <GameplayKit/GKVoronoiNoiseSource.h>
#import <GameplayKit/GKNoiseSource.h>
#import <GameplayKit/GKNoiseSourceUtils.h>
#import <GameplayKit/GKNoise.h>
#import <GameplayKit/GKNoiseModifier.h>
#import <GameplayKit/GKAbsoluteValueNoiseModifier.h>
#import <GameplayKit/GKClampNoiseModifier.h>
#import <GameplayKit/GKConstantPowerNoiseModifier.h>
#import <GameplayKit/GKInvertNoiseModifier.h>
#import <GameplayKit/GKTurbulenceNoiseModifier.h>
#import <GameplayKit/GKCurveNoiseModifier.h>
#import <GameplayKit/GKTerraceNoiseModifier.h>
#import <GameplayKit/GKMoveNoiseModifier.h>
#import <GameplayKit/GKScaleNoiseModifier.h>
#import <GameplayKit/GKRotateNoiseModifier.h>
#import <GameplayKit/GKAddNoiseModifier.h>
#import <GameplayKit/GKMultiplyNoiseModifier.h>
#import <GameplayKit/GKMinimumNoiseModifier.h>
#import <GameplayKit/GKMaximumNoiseModifier.h>
#import <GameplayKit/GKPowerNoiseModifier.h>
#import <GameplayKit/GKDisplaceNoiseModifier.h>
#import <GameplayKit/GKBlendNoiseModifier.h>
#import <GameplayKit/GKState.h>
#import <GameplayKit/GKCoherentNoiseSource.h>
#import <GameplayKit/GKComponent.h>
#import <GameplayKit/GKComponentSystem.h>
#import <GameplayKit/GKGraphNode.h>
#import <GameplayKit/GKGraphNode2D.h>
#import <GameplayKit/GKGraphNode3D.h>
#import <GameplayKit/GKGridGraphNode.h>
#import <GameplayKit/GKConstantNoiseSource.h>
#import <GameplayKit/GKPerlinNoiseSource.h>
#import <GameplayKit/GKOctreeNode.h>
#import <GameplayKit/GKOctree.h>
#import <GameplayKit/GKStateMachine.h>
#import <GameplayKit/GKBehavior.h>
#import <GameplayKit/GKPath.h>
#import <GameplayKit/GKGoal.h>
#import <GameplayKit/GKSpheresNoiseSource.h>
#import <GameplayKit/GKSCNNodeComponent.h>
#import <GameplayKit/GKCompositeBehavior.h>
#import <GameplayKit/GKObstacleGraph.h>
#import <GameplayKit/GKScene.h>
#import <GameplayKit/GKCustomClassUnarchiver.h>
#import <GameplayKit/GKGridGraph.h>
#import <GameplayKit/GKMersenneTwisterRandomSource.h>

void* GKClosestPointsBetweenLineSegments(void);
void* GKDoesCircleIntersectLine(void);
void* GKDoesCircleIntersectLineSegment(void);
void* GKDoesCircleIntersectPolygon(void);
void* GKGetCircleToLineIntersectionPoints(void);
void* GKGetCircleToLineSegmentIntersectionPoints(void);
void* GKGetClosestPointOnLineSegmentToPoint(void);
void* GKGetLineSegmentToLineSegmentIntersectionPoint(void);
void* GKGetLineToLineIntersection(void);
void* _Z10GKFindPathP11GKGraphNodeS0_(void);
void* _Z10GKFindPathP12GKCGraphNodeS0_RNSt3__16vectorIS0_NS1_9allocatorIS0_EEEE(void);
void* _Z11orientationDv2_fS_S_(void);
void* _Z11pointOnLineDv2_fS_S_(void);
void* _Z14__voronoiNoiseDv3_fffa(void);
void* _Z16MakeVectorFloat2ff(void);
void* _Z16MakeVectorFloat3fff(void);
void* _Z16getCoherentNoiseDv3_dDv3_ii(void);
void* _Z24getGradientCoherentNoiseDv3_di(void);
void* _Z33GKDoesLineSegmentIntersectPolygonPDv2_fiS_S_(void);
void* _Z41GKGetLineSegmentPolygonIntersectionPointsPDv2_fiS_S_(void);
void* _Z4lerpddd(void);
void* _Z5Clampfff(void);
void* _Z5__lcgy(void);
void* _Z5hash3yyy(void);
void* _Z8curveMapd(void);
void* _Z8makeHeapPNSt3__16vectorIP12GKCGraphNodeNS_9allocatorIS2_EEEERNS_3mapIS2_fNS_4lessIS2_EENS3_INS_4pairIKS2_fEEEEEE(void);
void* _Z8makeHeapPNSt3__16vectorIU8__strongP11GKGraphNodeNS_9allocatorIS3_EEEERNS_3mapIS3_fNS_4lessIS3_EENS4_INS_4pairIU8__strongKS2_fEEEEEE(void);
void* _ZN10ClipperLib10GetOverlapExxxxRxS0_(void);
void* _ZN10ClipperLib10PointCountEPNS_5OutPtE(void);
void* _ZN10ClipperLib10RemoveEdgeEPNS_5TEdgeE(void);
void* _ZN10ClipperLib10SwapPointsERNS_8IntPointES1_(void);
void* _ZN10ClipperLib11ClipperBase12ProcessBoundEPNS_5TEdgeEb(void);
void* _ZN10ClipperLib11ClipperBase14PopLocalMinimaEv(void);
void* _ZN10ClipperLib11ClipperBase22DisposeLocalMinimaListEv(void);
void* _ZN10ClipperLib11ClipperBase5ClearEv(void);
void* _ZN10ClipperLib11ClipperBase5ResetEv(void);
void* _ZN10ClipperLib11ClipperBase7AddPathERKNSt3__16vectorINS_8IntPointENS1_9allocatorIS3_EEEENS_8PolyTypeEb(void);
void* _ZN10ClipperLib11ClipperBase8AddPathsERKNSt3__16vectorINS2_INS_8IntPointENS1_9allocatorIS3_EEEENS4_IS6_EEEENS_8PolyTypeEb(void);
void* _ZN10ClipperLib11ClipperBase9GetBoundsEv(void);
void* _ZN10ClipperLib11ClipperBaseC1Ev(void);
void* _ZN10ClipperLib11ClipperBaseC2Ev(void);
void* _ZN10ClipperLib11ClipperBaseD0Ev(void);
void* _ZN10ClipperLib11ClipperBaseD1Ev(void);
void* _ZN10ClipperLib11ClipperBaseD2Ev(void);
void* _ZN10ClipperLib11GetBottomPtEPNS_5OutPtE(void);
void* _ZN10ClipperLib11OrientationERKNSt3__16vectorINS_8IntPointENS0_9allocatorIS2_EEEE(void);
void* _ZN10ClipperLib11ReversePathERNSt3__16vectorINS_8IntPointENS0_9allocatorIS2_EEEE(void);
void* _ZN10ClipperLib11SlopesEqualENS_8IntPointES0_S0_S0_b(void);
void* _ZN10ClipperLib11SlopesEqualENS_8IntPointES0_S0_b(void);
void* _ZN10ClipperLib11SlopesEqualERKNS_5TEdgeES2_b(void);
void* _ZN10ClipperLib12CleanPolygonERKNSt3__16vectorINS_8IntPointENS0_9allocatorIS2_EEEERS5_d(void);
void* _ZN10ClipperLib12CleanPolygonERNSt3__16vectorINS_8IntPointENS0_9allocatorIS2_EEEEd(void);
void* _ZN10ClipperLib12GetNextInAELEPNS_5TEdgeENS_9DirectionE(void);
void* _ZN10ClipperLib12MinkowskiSumERKNSt3__16vectorINS_8IntPointENS0_9allocatorIS2_EEEERKNS1_IS5_NS3_IS5_EEEERS9_b(void);
void* _ZN10ClipperLib12MinkowskiSumERKNSt3__16vectorINS_8IntPointENS0_9allocatorIS2_EEEES7_RNS1_IS5_NS3_IS5_EEEEb(void);
void* _ZN10ClipperLib12ReversePathsERNSt3__16vectorINS1_INS_8IntPointENS0_9allocatorIS2_EEEENS3_IS5_EEEE(void);
void* _ZN10ClipperLib13CleanPolygonsERKNSt3__16vectorINS1_INS_8IntPointENS0_9allocatorIS2_EEEENS3_IS5_EEEERS7_d(void);
void* _ZN10ClipperLib13CleanPolygonsERNSt3__16vectorINS1_INS_8IntPointENS0_9allocatorIS2_EEEENS3_IS5_EEEEd(void);
void* _ZN10ClipperLib13ClipperOffset11OffsetPointEiRiNS_8JoinTypeE(void);
void* _ZN10ClipperLib13ClipperOffset15FixOrientationsEv(void);
void* _ZN10ClipperLib13ClipperOffset5ClearEv(void);
void* _ZN10ClipperLib13ClipperOffset7AddPathERKNSt3__16vectorINS_8IntPointENS1_9allocatorIS3_EEEENS_8JoinTypeENS_7EndTypeE(void);
void* _ZN10ClipperLib13ClipperOffset7DoMiterEiid(void);
void* _ZN10ClipperLib13ClipperOffset7DoRoundEii(void);
void* _ZN10ClipperLib13ClipperOffset7ExecuteERNS_8PolyTreeEd(void);
void* _ZN10ClipperLib13ClipperOffset7ExecuteERNSt3__16vectorINS2_INS_8IntPointENS1_9allocatorIS3_EEEENS4_IS6_EEEEd(void);
void* _ZN10ClipperLib13ClipperOffset8AddPathsERKNSt3__16vectorINS2_INS_8IntPointENS1_9allocatorIS3_EEEENS4_IS6_EEEENS_8JoinTypeENS_7EndTypeE(void);
void* _ZN10ClipperLib13ClipperOffset8DoOffsetEd(void);
void* _ZN10ClipperLib13ClipperOffset8DoSquareEii(void);
void* _ZN10ClipperLib13ClipperOffsetC1Edd(void);
void* _ZN10ClipperLib13ClipperOffsetC2Edd(void);
void* _ZN10ClipperLib13ClipperOffsetD1Ev(void);
void* _ZN10ClipperLib13ClipperOffsetD2Ev(void);
void* _ZN10ClipperLib13DisposeOutPtsERPNS_5OutPtE(void);
void* _ZN10ClipperLib13GetMaximaPairEPNS_5TEdgeE(void);
void* _ZN10ClipperLib13GetUnitNormalERKNS_8IntPointES2_(void);
void* _ZN10ClipperLib13MinkowskiDiffERKNSt3__16vectorINS_8IntPointENS0_9allocatorIS2_EEEES7_RNS1_IS5_NS3_IS5_EEEE(void);
void* _ZN10ClipperLib13PointIsVertexERKNS_8IntPointEPNS_5OutPtE(void);
void* _ZN10ClipperLib13TranslatePathERKNSt3__16vectorINS_8IntPointENS0_9allocatorIS2_EEEERS5_S2_(void);
void* _ZN10ClipperLib14FindNextLocMinEPNS_5TEdgeE(void);
void* _ZN10ClipperLib14IntersectPointERNS_5TEdgeES1_RNS_8IntPointE(void);
void* _ZN10ClipperLib14PointInPolygonERKNS_8IntPointEPNS_5OutPtE(void);
void* _ZN10ClipperLib14PointInPolygonERKNS_8IntPointERKNSt3__16vectorIS0_NS3_9allocatorIS0_EEEE(void);
void* _ZN10ClipperLib14PointsAreCloseENS_8IntPointES0_d(void);
void* _ZN10ClipperLib15FirstIsBottomPtEPKNS_5OutPtES2_(void);
void* _ZN10ClipperLib15GetLowermostRecEPNS_6OutRecES1_(void);
void* _ZN10ClipperLib15PolyTreeToPathsERKNS_8PolyTreeERNSt3__16vectorINS4_INS_8IntPointENS3_9allocatorIS5_EEEENS6_IS8_EEEE(void);
void* _ZN10ClipperLib15SimplifyPolygonERKNSt3__16vectorINS_8IntPointENS0_9allocatorIS2_EEEERNS1_IS5_NS3_IS5_EEEENS_12PolyFillTypeE(void);
void* _ZN10ClipperLib16GetHorzDirectionERNS_5TEdgeERNS_9DirectionERxS4_(void);
void* _ZN10ClipperLib16SimplifyPolygonsERKNSt3__16vectorINS1_INS_8IntPointENS0_9allocatorIS2_EEEENS3_IS5_EEEERS7_NS_12PolyFillTypeE(void);
void* _ZN10ClipperLib16SimplifyPolygonsERNSt3__16vectorINS1_INS_8IntPointENS0_9allocatorIS2_EEEENS3_IS5_EEEENS_12PolyFillTypeE(void);
void* _ZN10ClipperLib17GetOverlapSegmentENS_8IntPointES0_S0_S0_RS0_S1_(void);
void* _ZN10ClipperLib17IntersectListSortEPNS_13IntersectNodeES1_(void);
void* _ZN10ClipperLib18AddPolyNodeToPathsERKNS_8PolyNodeENS_8NodeTypeERNSt3__16vectorINS5_INS_8IntPointENS4_9allocatorIS6_EEEENS7_IS9_EEEE(void);
void* _ZN10ClipperLib18Poly2ContainsPoly1EPNS_5OutPtES1_(void);
void* _ZN10ClipperLib18ReversePolyPtLinksEPNS_5OutPtE(void);
void* _ZN10ClipperLib18SwapIntersectNodesERNS_13IntersectNodeES1_(void);
void* _ZN10ClipperLib19HorzSegmentsOverlapExxxx(void);
void* _ZN10ClipperLib19Param1RightOfParam2EPNS_6OutRecES1_(void);
void* _ZN10ClipperLib19SlopesNearCollinearERKNS_8IntPointES2_S2_d(void);
void* _ZN10ClipperLib20DistanceFromLineSqrdERKNS_8IntPointES2_S2_(void);
void* _ZN10ClipperLib21OpenPathsFromPolyTreeERNS_8PolyTreeERNSt3__16vectorINS3_INS_8IntPointENS2_9allocatorIS4_EEEENS5_IS7_EEEE(void);
void* _ZN10ClipperLib21Pt2IsBetweenPt1AndPt3ENS_8IntPointES0_S0_(void);
void* _ZN10ClipperLib23ClosedPathsFromPolyTreeERKNS_8PolyTreeERNSt3__16vectorINS4_INS_8IntPointENS3_9allocatorIS5_EEEENS6_IS8_EEEE(void);
void* _ZN10ClipperLib4AreaERKNS_6OutRecE(void);
void* _ZN10ClipperLib4AreaERKNSt3__16vectorINS_8IntPointENS0_9allocatorIS2_EEEE(void);
void* _ZN10ClipperLib4SwapERxS0_(void);
void* _ZN10ClipperLib7Clipper10ClearJoinsEv(void);
void* _ZN10ClipperLib7Clipper10JoinPointsEPNS_4JoinEPNS_6OutRecES4_(void);
void* _ZN10ClipperLib7Clipper11BuildResultERNSt3__16vectorINS2_INS_8IntPointENS1_9allocatorIS3_EEEENS4_IS6_EEEE(void);
void* _ZN10ClipperLib7Clipper11PopScanbeamEv(void);
void* _ZN10ClipperLib7Clipper12AddEdgeToSELEPNS_5TEdgeE(void);
void* _ZN10ClipperLib7Clipper12AddGhostJoinEPNS_5OutPtENS_8IntPointE(void);
void* _ZN10ClipperLib7Clipper12BuildResult2ERNS_8PolyTreeE(void);
void* _ZN10ClipperLib7Clipper12CopyAELToSELEv(void);
void* _ZN10ClipperLib7Clipper12CreateOutRecEv(void);
void* _ZN10ClipperLib7Clipper12SetHoleStateEPNS_5TEdgeEPNS_6OutRecE(void);
void* _ZN10ClipperLib7Clipper13AppendPolygonEPNS_5TEdgeES2_(void);
void* _ZN10ClipperLib7Clipper13DeleteFromAELEPNS_5TEdgeE(void);
void* _ZN10ClipperLib7Clipper13DeleteFromSELEPNS_5TEdgeE(void);
void* _ZN10ClipperLib7Clipper13DisposeOutRecEm(void);
void* _ZN10ClipperLib7Clipper14FixHoleLinkageERNS_6OutRecE(void);
void* _ZN10ClipperLib7Clipper14InsertScanbeamEx(void);
void* _ZN10ClipperLib7Clipper14IntersectEdgesEPNS_5TEdgeES2_RNS_8IntPointE(void);
void* _ZN10ClipperLib7Clipper15AddLocalMaxPolyEPNS_5TEdgeES2_RKNS_8IntPointE(void);
void* _ZN10ClipperLib7Clipper15AddLocalMinPolyEPNS_5TEdgeES2_RKNS_8IntPointE(void);
void* _ZN10ClipperLib7Clipper15ClearGhostJoinsEv(void);
void* _ZN10ClipperLib7Clipper15ExecuteInternalEv(void);
void* _ZN10ClipperLib7Clipper15FixupOutPolygonERNS_6OutRecE(void);
void* _ZN10ClipperLib7Clipper15JoinCommonEdgesEv(void);
void* _ZN10ClipperLib7Clipper15SetWindingCountERNS_5TEdgeE(void);
void* _ZN10ClipperLib7Clipper16DoSimplePolygonsEv(void);
void* _ZN10ClipperLib7Clipper16FixupFirstLefts1EPNS_6OutRecES2_(void);
void* _ZN10ClipperLib7Clipper16FixupFirstLefts2EPNS_6OutRecES2_(void);
void* _ZN10ClipperLib7Clipper17DisposeAllOutRecsEv(void);
void* _ZN10ClipperLib7Clipper17InsertEdgeIntoAELEPNS_5TEdgeES2_(void);
void* _ZN10ClipperLib7Clipper17ProcessHorizontalEPNS_5TEdgeEb(void);
void* _ZN10ClipperLib7Clipper17UpdateEdgeIntoAELERPNS_5TEdgeE(void);
void* _ZN10ClipperLib7Clipper18BuildIntersectListEx(void);
void* _ZN10ClipperLib7Clipper18ProcessHorizontalsEb(void);
void* _ZN10ClipperLib7Clipper18SwapPositionsInAELEPNS_5TEdgeES2_(void);
void* _ZN10ClipperLib7Clipper18SwapPositionsInSELEPNS_5TEdgeES2_(void);
void* _ZN10ClipperLib7Clipper20ProcessIntersectListEv(void);
void* _ZN10ClipperLib7Clipper20ProcessIntersectionsEx(void);
void* _ZN10ClipperLib7Clipper21DisposeIntersectNodesEv(void);
void* _ZN10ClipperLib7Clipper22FixupIntersectionOrderEv(void);
void* _ZN10ClipperLib7Clipper24InsertLocalMinimaIntoAELEx(void);
void* _ZN10ClipperLib7Clipper27ProcessEdgesAtTopOfScanbeamEx(void);
void* _ZN10ClipperLib7Clipper5ResetEv(void);
void* _ZN10ClipperLib7Clipper7AddJoinEPNS_5OutPtES2_NS_8IntPointE(void);
void* _ZN10ClipperLib7Clipper7ExecuteENS_8ClipTypeERNS_8PolyTreeENS_12PolyFillTypeES4_(void);
void* _ZN10ClipperLib7Clipper7ExecuteENS_8ClipTypeERNSt3__16vectorINS3_INS_8IntPointENS2_9allocatorIS4_EEEENS5_IS7_EEEENS_12PolyFillTypeESB_(void);
void* _ZN10ClipperLib7Clipper8AddOutPtEPNS_5TEdgeERKNS_8IntPointE(void);
void* _ZN10ClipperLib7Clipper8DoMaximaEPNS_5TEdgeE(void);
void* _ZN10ClipperLib7Clipper9GetOutRecEi(void);
void* _ZN10ClipperLib7ClipperC1Ei(void);
void* _ZN10ClipperLib7ClipperC2Ei(void);
void* _ZN10ClipperLib7ClipperD0Ev(void);
void* _ZN10ClipperLib7ClipperD1Ev(void);
void* _ZN10ClipperLib7ClipperD2Ev(void);
void* _ZN10ClipperLib8DupOutPtEPNS_5OutPtEb(void);
void* _ZN10ClipperLib8JoinHorzEPNS_5OutPtES1_S1_S1_NS_8IntPointEb(void);
void* _ZN10ClipperLib8PolyNode8AddChildERS0_(void);
void* _ZN10ClipperLib8PolyNodeC1Ev(void);
void* _ZN10ClipperLib8PolyNodeC2Ev(void);
void* _ZN10ClipperLib8PolyTree5ClearEv(void);
void* _ZN10ClipperLib9ExcludeOpEPNS_5OutPtE(void);
void* _ZN10ClipperLib9InitEdge2ERNS_5TEdgeENS_8PolyTypeE(void);
void* _ZN10ClipperLib9Int128MulExx(void);
void* _ZN10ClipperLib9MinkowskiERKNSt3__16vectorINS_8IntPointENS0_9allocatorIS2_EEEES7_RNS1_IS5_NS3_IS5_EEEEbb(void);
void* _ZN10ClipperLib9RangeTestERKNS_8IntPointERb(void);
void* _ZN10ClipperLiblsERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEERKNS0_6vectorINS6_INS_8IntPointENS0_9allocatorIS7_EEEENS8_ISA_EEEE(void);
void* _ZN10ClipperLiblsERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEERKNS0_6vectorINS_8IntPointENS0_9allocatorIS7_EEEE(void);
void* _ZN10ClipperLiblsERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEERKNS_8IntPointE(void);
void* _ZN12GKCGraphNode10costToNodeEPS_(void);
void* _ZN12GKCGraphNode19addConnectionToNodeEPS_b(void);
void* _ZN12GKCGraphNode19estimatedCostToNodeEPS_(void);
void* _ZN12GKCGraphNode22removeConnectionToNodeEPS_b(void);
void* _ZN12GKCGraphNodeC1Ev(void);
void* _ZN12GKCGraphNodeC2Ev(void);
void* _ZN12GKCGraphNodeD0Ev(void);
void* _ZN12GKCGraphNodeD1Ev(void);
void* _ZN12GKCGraphNodeD2Ev(void);
void* _ZN12GKCGridGraph10removeNodeEP12GKCGraphNode(void);
void* _ZN12GKCGridGraph18addNodeToGridNodesEP16GKCGridGraphNode(void);
void* _ZN12GKCGridGraph18nodeAtGridPositionEDv2_i(void);
void* _ZN12GKCGridGraph22initDontConstructNodesEDv2_ijjbP10objc_class(void);
void* _ZN12GKCGridGraph26connectNodeToAdjacentNodesEP16GKCGridGraphNode(void);
void* _ZN12GKCGridGraph29nodeAtGridPositionNoNullCheckEDv2_i(void);
void* _ZN12GKCGridGraph31connectNodeToAdjacentNodesNoAddEP16GKCGridGraphNodeb(void);
void* _ZN12GKCGridGraph4initEDv2_ijjbP10objc_class(void);
void* _ZN12GKCGridGraphC1Ev(void);
void* _ZN12GKCGridGraphC2Ev(void);
void* _ZN12GKCGridGraphD0Ev(void);
void* _ZN12GKCGridGraphD1Ev(void);
void* _ZN12GKCGridGraphD2Ev(void);
void* _ZN12GKCMeshGraph11AddObstacleEP18GKCPolygonObstacle(void);
void* _ZN12GKCMeshGraph11TriangulateEv(void);
void* _ZN12GKCMeshGraph12GetTrianglesEv(void);
void* _ZN12GKCMeshGraph14RemoveObstacleEP18GKCPolygonObstacle(void);
void* _ZN12GKCMeshGraph15GetNumTrianglesEv(void);
void* _ZN12GKCMeshGraph15TriangleAtIndexEi(void);
void* _ZN12GKCMeshGraph23BuildGraphFromTrianglesEv(void);
void* _ZN12GKCMeshGraph25ConnectNodeUsingObstaclesEP14GKCGraphNode2D(void);
void* _ZN12GKCMeshGraphC1Ev(void);
void* _ZN12GKCMeshGraphC2Ev(void);
void* _ZN12GKCMeshGraphD0Ev(void);
void* _ZN12GKCMeshGraphD1Ev(void);
void* _ZN12GKCMeshGraphD2Ev(void);
void* _ZN14GKCGraphNode2D10costToNodeEP12GKCGraphNode(void);
void* _ZN14GKCGraphNode2D19estimatedCostToNodeEP12GKCGraphNode(void);
void* _ZN14GKCGraphNode2DC1EDv2_f(void);
void* _ZN14GKCGraphNode2DC1Ev(void);
void* _ZN14GKCGraphNode2DC2EDv2_f(void);
void* _ZN14GKCGraphNode2DC2Ev(void);
void* _ZN14GKCGraphNode3D10costToNodeEP12GKCGraphNode(void);
void* _ZN14GKCGraphNode3D19estimatedCostToNodeEP12GKCGraphNode(void);
void* _ZN14GKCGraphNode3DC1EDv3_f(void);
void* _ZN14GKCGraphNode3DC1Ev(void);
void* _ZN14GKCGraphNode3DC2EDv3_f(void);
void* _ZN14GKCGraphNode3DC2Ev(void);
void* _ZN16GKCGridGraphNode10costToNodeEP12GKCGraphNode(void);
void* _ZN16GKCGridGraphNode19estimatedCostToNodeEP12GKCGraphNode(void);
void* _ZN16GKCGridGraphNodeC1EDv2_i(void);
void* _ZN16GKCGridGraphNodeC1Ev(void);
void* _ZN16GKCGridGraphNodeC2EDv2_i(void);
void* _ZN16GKCGridGraphNodeC2Ev(void);
void* _ZN16GKCGridGraphNodeD0Ev(void);
void* _ZN16GKCGridGraphNodeD1Ev(void);
void* _ZN16GKCGridGraphNodeD2Ev(void);
void* _ZN16GKCObstacleGraph11addObstacleEP18GKCPolygonObstacle(void);
void* _ZN16GKCObstacleGraph11addObstacleEP18GKCPolygonObstacleb(void);
void* _ZN16GKCObstacleGraph14removeObstacleEP18GKCPolygonObstacle(void);
void* _ZN16GKCObstacleGraph15extrudeObstacleEP18GKCPolygonObstacle(void);
void* _ZN16GKCObstacleGraph16nodesForObstacleEP18GKCPolygonObstacle(void);
void* _ZN16GKCObstacleGraph18removeAllObstaclesEv(void);
void* _ZN16GKCObstacleGraph22lockConnectionFromNodeEP14GKCGraphNode2DS1_(void);
void* _ZN16GKCObstacleGraph24unlockConnectionFromNodeEP14GKCGraphNode2DS1_(void);
void* _ZN16GKCObstacleGraph25connectNodeUsingObstaclesEP14GKCGraphNode2D(void);
void* _ZN16GKCObstacleGraph25isConnectedLockedFromNodeEP14GKCGraphNode2DS1_(void);
void* _ZN16GKCObstacleGraph30restoreObstacleNodeConnectionsEv(void);
void* _ZN16GKCObstacleGraph31connectNodeToNodeUsingObstaclesEP14GKCGraphNode2DS1_P7NSArrayIP17GKPolygonObstacleE(void);
void* _ZN16GKCObstacleGraph36extrudeObstacleAndGenerateGraphNodesEP18GKCPolygonObstacleRNSt3__16vectorIU8__strongP13GKGraphNode2DNS2_9allocatorIS6_EEEE(void);
void* _ZN16GKCObstacleGraph42connectNodeUsingObstaclesIgnoringObstaclesEP14GKCGraphNode2DP7NSArrayIP17GKPolygonObstacleE(void);
void* _ZN16GKCObstacleGraph49connectNodeToNodeUsingObstaclesIgnoreBufferRadiusEP14GKCGraphNode2DS1_P7NSArrayIP17GKPolygonObstacleE(void);
void* _ZN16GKCObstacleGraph56connectNodeUsingObstaclesIgnoringBufferRadiusOfObstaclesEP14GKCGraphNode2DP7NSArrayIP17GKPolygonObstacleE(void);
void* _ZN16GKCObstacleGraphC1Ev(void);
void* _ZN16GKCObstacleGraphC2Ev(void);
void* _ZN16GKCObstacleGraphD0Ev(void);
void* _ZN16GKCObstacleGraphD1Ev(void);
void* _ZN16GKCObstacleGraphD2Ev(void);
void* _ZN18GKCPolygonObstacle15extrudeObstacleEPS_f(void);
void* _ZN18GKCPolygonObstacleC1EPDv2_fm(void);
void* _ZN18GKCPolygonObstacleC2EPDv2_fm(void);
void* _ZN18GKCPolygonObstacleD0Ev(void);
void* _ZN18GKCPolygonObstacleD1Ev(void);
void* _ZN18GKCPolygonObstacleD2Ev(void);
void* _ZN20GKTriangleGraphNodesC1Ev(void);
void* _ZN20GKTriangleGraphNodesC2Ev(void);
void* _ZN3p2t10InScanAreaERNS_5PointES1_S1_S1_(void);
void* _ZN3p2t12SweepContext10LocateNodeERNS_5PointE(void);
void* _ZN3p2t12SweepContext10RemoveNodeEPNS_4NodeE(void);
void* _ZN3p2t12SweepContext12GetTrianglesEv(void);
void* _ZN3p2t12SweepContext13RemoveFromMapEPNS_8TriangleE(void);
void* _ZN3p2t12SweepContext17InitTriangulationEv(void);
void* _ZN3p2t12SweepContext18MapTriangleToNodesERNS_8TriangleE(void);
void* _ZN3p2t12SweepContext20CreateAdvancingFrontENSt3__16vectorIPNS_4NodeENS1_9allocatorIS4_EEEE(void);
void* _ZN3p2t12SweepContext6GetMapEv(void);
void* _ZN3p2t12SweepContext7AddHoleENSt3__16vectorIPNS_5PointENS1_9allocatorIS4_EEEE(void);
void* _ZN3p2t12SweepContext8AddPointEPNS_5PointE(void);
void* _ZN3p2t12SweepContext8AddToMapEPNS_8TriangleE(void);
void* _ZN3p2t12SweepContext8GetPointERKi(void);
void* _ZN3p2t12SweepContext9InitEdgesENSt3__16vectorIPNS_5PointENS1_9allocatorIS4_EEEE(void);
void* _ZN3p2t12SweepContext9MeshCleanERNS_8TriangleE(void);
void* _ZN3p2t12SweepContextC1ENSt3__16vectorIPNS_5PointENS1_9allocatorIS4_EEEE(void);
void* _ZN3p2t12SweepContextC2ENSt3__16vectorIPNS_5PointENS1_9allocatorIS4_EEEE(void);
void* _ZN3p2t12SweepContextD1Ev(void);
void* _ZN3p2t12SweepContextD2Ev(void);
void* _ZN3p2t14AdvancingFront10LocateNodeERKd(void);
void* _ZN3p2t14AdvancingFront11LocatePointEPKNS_5PointE(void);
void* _ZN3p2t14AdvancingFront14FindSearchNodeERKd(void);
void* _ZN3p2t14AdvancingFrontC1ERNS_4NodeES2_(void);
void* _ZN3p2t14AdvancingFrontC2ERNS_4NodeES2_(void);
void* _ZN3p2t14AdvancingFrontD1Ev(void);
void* _ZN3p2t14AdvancingFrontD2Ev(void);
void* _ZN3p2t3CDT11TriangulateEv(void);
void* _ZN3p2t3CDT12GetTrianglesEv(void);
void* _ZN3p2t3CDT6GetMapEv(void);
void* _ZN3p2t3CDT7AddHoleENSt3__16vectorIPNS_5PointENS1_9allocatorIS4_EEEE(void);
void* _ZN3p2t3CDT8AddPointEPNS_5PointE(void);
void* _ZN3p2t3CDTC1ENSt3__16vectorIPNS_5PointENS1_9allocatorIS4_EEEE(void);
void* _ZN3p2t3CDTC2ENSt3__16vectorIPNS_5PointENS1_9allocatorIS4_EEEE(void);
void* _ZN3p2t3CDTD1Ev(void);
void* _ZN3p2t3CDTD2Ev(void);
void* _ZN3p2t5Sweep10BasinAngleERNS_4NodeE(void);
void* _ZN3p2t5Sweep10PointEventERNS_12SweepContextERNS_5PointE(void);
void* _ZN3p2t5Sweep11SweepPointsERNS_12SweepContextE(void);
void* _ZN3p2t5Sweep11TriangulateERNS_12SweepContextE(void);
void* _ZN3p2t5Sweep12FillBasinReqERNS_12SweepContextEPNS_4NodeE(void);
void* _ZN3p2t5Sweep13FillEdgeEventERNS_12SweepContextEPNS_4EdgeEPNS_4NodeE(void);
void* _ZN3p2t5Sweep13FlipEdgeEventERNS_12SweepContextERNS_5PointES4_PNS_8TriangleES4_(void);
void* _ZN3p2t5Sweep13NextFlipPointERNS_5PointES2_RNS_8TriangleES2_(void);
void* _ZN3p2t5Sweep16NewFrontTriangleERNS_12SweepContextERNS_5PointERNS_4NodeE(void);
void* _ZN3p2t5Sweep16NextFlipTriangleERNS_12SweepContextEiRNS_8TriangleES4_RNS_5PointES6_(void);
void* _ZN3p2t5Sweep17FlipScanEdgeEventERNS_12SweepContextERNS_5PointES4_RNS_8TriangleES6_S4_(void);
void* _ZN3p2t5Sweep18FillAdvancingFrontERNS_12SweepContextERNS_4NodeE(void);
void* _ZN3p2t5Sweep18LargeHole_DontFillEPNS_4NodeE(void);
void* _ZN3p2t5Sweep18RotateTrianglePairERNS_8TriangleERNS_5PointES2_S4_(void);
void* _ZN3p2t5Sweep19FinalizationPolygonERNS_12SweepContextE(void);
void* _ZN3p2t5Sweep20IsEdgeSideOfTriangleERNS_8TriangleERNS_5PointES4_(void);
void* _ZN3p2t5Sweep21AngleExceeds90DegreesEPNS_5PointES2_S2_(void);
void* _ZN3p2t5Sweep22FillLeftAboveEdgeEventERNS_12SweepContextEPNS_4EdgeEPNS_4NodeE(void);
void* _ZN3p2t5Sweep22FillLeftBelowEdgeEventERNS_12SweepContextEPNS_4EdgeERNS_4NodeE(void);
void* _ZN3p2t5Sweep23FillLeftConvexEdgeEventERNS_12SweepContextEPNS_4EdgeERNS_4NodeE(void);
void* _ZN3p2t5Sweep23FillRightAboveEdgeEventERNS_12SweepContextEPNS_4EdgeEPNS_4NodeE(void);
void* _ZN3p2t5Sweep23FillRightBelowEdgeEventERNS_12SweepContextEPNS_4EdgeERNS_4NodeE(void);
void* _ZN3p2t5Sweep24FillLeftConcaveEdgeEventERNS_12SweepContextEPNS_4EdgeERNS_4NodeE(void);
void* _ZN3p2t5Sweep24FillRightConvexEdgeEventERNS_12SweepContextEPNS_4EdgeERNS_4NodeE(void);
void* _ZN3p2t5Sweep25FillRightConcaveEdgeEventERNS_12SweepContextEPNS_4EdgeERNS_4NodeE(void);
void* _ZN3p2t5Sweep37AngleExceedsPlus90DegreesOrIsNegativeEPNS_5PointES2_S2_(void);
void* _ZN3p2t5Sweep4FillERNS_12SweepContextERNS_4NodeE(void);
void* _ZN3p2t5Sweep5AngleERNS_5PointES2_S2_(void);
void* _ZN3p2t5Sweep8IncircleERNS_5PointES2_S2_S2_(void);
void* _ZN3p2t5Sweep8LegalizeERNS_12SweepContextERNS_8TriangleE(void);
void* _ZN3p2t5Sweep9EdgeEventERNS_12SweepContextEPNS_4EdgeEPNS_4NodeE(void);
void* _ZN3p2t5Sweep9EdgeEventERNS_12SweepContextERNS_5PointES4_PNS_8TriangleES4_(void);
void* _ZN3p2t5Sweep9FillBasinERNS_12SweepContextERNS_4NodeE(void);
void* _ZN3p2t5Sweep9HoleAngleERNS_4NodeE(void);
void* _ZN3p2t5Sweep9IsShallowERNS_12SweepContextERNS_4NodeE(void);
void* _ZN3p2t5SweepD1Ev(void);
void* _ZN3p2t5SweepD2Ev(void);
void* _ZN3p2t8Orient2dERNS_5PointES1_S1_(void);
void* _ZN3p2t8Triangle10DebugPrintEv(void);
void* _ZN3p2t8Triangle10NeighborCWERNS_5PointE(void);
void* _ZN3p2t8Triangle11NeighborCCWERNS_5PointE(void);
void* _ZN3p2t8Triangle12MarkNeighborEPNS_5PointES2_PS0_(void);
void* _ZN3p2t8Triangle12MarkNeighborERS0_(void);
void* _ZN3p2t8Triangle13ClearNeighborEPS0_(void);
void* _ZN3p2t8Triangle13OppositePointERS0_RNS_5PointE(void);
void* _ZN3p2t8Triangle14ClearNeighborsEv(void);
void* _ZN3p2t8Triangle14NeighborAcrossERNS_5PointE(void);
void* _ZN3p2t8Triangle16GetDelunayEdgeCWERNS_5PointE(void);
void* _ZN3p2t8Triangle16SetDelunayEdgeCWERNS_5PointEb(void);
void* _ZN3p2t8Triangle17ClearDelunayEdgesEv(void);
void* _ZN3p2t8Triangle17GetDelunayEdgeCCWERNS_5PointE(void);
void* _ZN3p2t8Triangle17SetDelunayEdgeCCWERNS_5PointEb(void);
void* _ZN3p2t8Triangle19MarkConstrainedEdgeEPNS_5PointES2_(void);
void* _ZN3p2t8Triangle19MarkConstrainedEdgeERNS_4EdgeE(void);
void* _ZN3p2t8Triangle19MarkConstrainedEdgeEi(void);
void* _ZN3p2t8Triangle20GetConstrainedEdgeCWERNS_5PointE(void);
void* _ZN3p2t8Triangle20SetConstrainedEdgeCWERNS_5PointEb(void);
void* _ZN3p2t8Triangle21GetConstrainedEdgeCCWERNS_5PointE(void);
void* _ZN3p2t8Triangle21SetConstrainedEdgeCCWERNS_5PointEb(void);
void* _ZN3p2t8Triangle5ClearEv(void);
void* _ZN3p2t8Triangle5IndexEPKNS_5PointE(void);
void* _ZN3p2t8Triangle7PointCWERNS_5PointE(void);
void* _ZN3p2t8Triangle8LegalizeERNS_5PointE(void);
void* _ZN3p2t8Triangle8LegalizeERNS_5PointES2_(void);
void* _ZN3p2t8Triangle8PointCCWERNS_5PointE(void);
void* _ZN3p2t8Triangle9EdgeIndexEPKNS_5PointES3_(void);
void* _ZN3p2t8TriangleC1ERNS_5PointES2_S2_(void);
void* _ZN3p2t8TriangleC2ERNS_5PointES2_S2_(void);
void* _ZN8GKCGraph10removeNodeEP12GKCGraphNode(void);
void* _ZN8GKCGraph27connectNodeToLowestCostNodeEP12GKCGraphNodeb(void);
void* _ZN8GKCGraph7addNodeEP12GKCGraphNode(void);
void* _ZN8GKCGraphC1Ev(void);
void* _ZN8GKCGraphC2Ev(void);
void* _ZN8GKCGraphD0Ev(void);
void* _ZN8GKCGraphD1Ev(void);
void* _ZN8GKCGraphD2Ev(void);
void* _ZN9OpenSteer13SimpleVehicle17applyBrakingForceEff(void);
void* _ZN9OpenSteer13SimpleVehicle18applySteeringForceERKNS_4Vec3Ef(void);
void* _ZN9OpenSteer13SimpleVehicle20measurePathCurvatureEf(void);
void* _ZN9OpenSteer13SimpleVehicle20regenerateLocalSpaceERKNS_4Vec3Ef(void);
void* _ZN9OpenSteer13SimpleVehicle22adjustRawSteeringForceERKNS_4Vec3Ef(void);
void* _ZN9OpenSteer13SimpleVehicle30annotationVelocityAccelerationEff(void);
void* _ZN9OpenSteer13SimpleVehicle30regenerateLocalSpaceForBankingERKNS_4Vec3Ef(void);
void* _ZN9OpenSteer13SimpleVehicleC1Ev(void);
void* _ZN9OpenSteer13SimpleVehicleC2Ev(void);
void* _ZN9OpenSteer13SimpleVehicleD1Ev(void);
void* _ZN9OpenSteer13SimpleVehicleD2Ev(void);
void* _ZN9OpenSteer15PolygonObstacle31findIntersectionWithVehiclePathERKNS_15AbstractVehicleERNS_16PathIntersectionEf(void);
void* _ZN9OpenSteer15PolygonObstacleC1ERNSt3__16vectorINS_4Vec3ENS1_9allocatorIS3_EEEE(void);
void* _ZN9OpenSteer15PolygonObstacleC1Ev(void);
void* _ZN9OpenSteer15PolygonObstacleC2ERNSt3__16vectorINS_4Vec3ENS1_9allocatorIS3_EEEE(void);
void* _ZN9OpenSteer15PolygonObstacleC2Ev(void);
void* _ZN9OpenSteer15PolylinePathway10initializeEiPKNS_4Vec3Efb(void);
void* _ZN9OpenSteer15PolylinePathway14mapPointToPathERKNS_4Vec3ERS1_Rf(void);
void* _ZN9OpenSteer15PolylinePathway22mapPathDistanceToPointEf(void);
void* _ZN9OpenSteer15PolylinePathway22mapPointToPathDistanceERKNS_4Vec3E(void);
void* _ZN9OpenSteer15PolylinePathway22pointToSegmentDistanceERKNS_4Vec3ES3_S3_(void);
void* _ZN9OpenSteer15PolylinePathwayC1EiPKNS_4Vec3Efb(void);
void* _ZN9OpenSteer15PolylinePathwayC2EiPKNS_4Vec3Efb(void);
void* _ZN9OpenSteer15PolylinePathwayD0Ev(void);
void* _ZN9OpenSteer15PolylinePathwayD1Ev(void);
void* _ZN9OpenSteer15PolylinePathwayD2Ev(void);
void* _ZN9OpenSteer21findPerpendicularIn3dERKNS_4Vec3E(void);
void* _ZN9OpenSteer29vecLimitDeviationAngleUtilityEbRKNS_4Vec3EfS2_(void);
void* _ZN9OpenSteer30RandomVectorInUnitRadiusSphereEv(void);
void* _ZN9OpenSteer30randomVectorOnUnitRadiusXZDiskEv(void);
void* _ZN9OpenSteer6PlugIn10applyToAllEPFvRS0_E(void);
void* _ZN9OpenSteer6PlugIn10findByNameEPKc(void);
void* _ZN9OpenSteer6PlugIn11findDefaultEv(void);
void* _ZN9OpenSteer6PlugIn13addToRegistryEv(void);
void* _ZN9OpenSteer6PlugIn20sortBySelectionOrderEv(void);
void* _ZN9OpenSteer6PlugIn4nextEv(void);
void* _ZN9OpenSteer6PlugInC2Ev(void);
void* _ZN9OpenSteer6PlugInD0Ev(void);
void* _ZN9OpenSteer6PlugInD1Ev(void);
void* _ZN9OpenSteer6PlugInD2Ev(void);
void* _ZNK10ClipperLib7Clipper14IsContributingERKNS_5TEdgeE(void);
void* _ZNK10ClipperLib7Clipper17IsEvenOddFillTypeERKNS_5TEdgeE(void);
void* _ZNK10ClipperLib7Clipper20IsEvenOddAltFillTypeERKNS_5TEdgeE(void);
void* _ZNK10ClipperLib8PolyNode10ChildCountEv(void);
void* _ZNK10ClipperLib8PolyNode16GetNextSiblingUpEv(void);
void* _ZNK10ClipperLib8PolyNode6IsHoleEv(void);
void* _ZNK10ClipperLib8PolyNode6IsOpenEv(void);
void* _ZNK10ClipperLib8PolyNode7GetNextEv(void);
void* _ZNK10ClipperLib8PolyTree5TotalEv(void);
void* _ZNK10ClipperLib8PolyTree8GetFirstEv(void);
void* _ZNK18GKCPolygonObstacle15intersectsPointEPKDv2_f(void);
void* _ZNK18GKCPolygonObstacle18intersectsLineFromEPKDv2_fS2_(void);
void* _ZNK9OpenSteer13SimpleVehicle21predictFuturePositionEf(void);
void* _ZNK9OpenSteer15PolygonObstacle12steerToAvoidERKNS_15AbstractVehicleEf(void);
void* _ZTv0_n24_N10ClipperLib7ClipperD0Ev(void);
void* _ZTv0_n24_N10ClipperLib7ClipperD1Ev(void);
void* _ZTv0_n24_N9OpenSteer15PolylinePathway14mapPointToPathERKNS_4Vec3ERS1_Rf(void);
void* _ZTv0_n32_N9OpenSteer15PolylinePathway22mapPathDistanceToPointEf(void);
void* _ZTv0_n40_N10ClipperLib7Clipper5ResetEv(void);
void* _ZTv0_n40_N9OpenSteer15PolylinePathway22mapPointToPathDistanceERKNS_4Vec3E(void);
void* lqAddToBin(void);
void* lqBinForLocation(void);
void* lqCreateDatabase(void);
void* lqDeleteDatabase(void);
void* lqFindNearestHelper(void);
void* lqFindNearestNeighborWithinRadius(void);
void* lqInitClientProxy(void);
void* lqInitDatabase(void);
void* lqMapOverAllObjects(void);
void* lqMapOverAllObjectsInBin(void);
void* lqMapOverAllObjectsInLocality(void);
void* lqMapOverAllObjectsInLocalityClipped(void);
void* lqMapOverAllOutsideObjects(void);
void* lqRemoveAllObjects(void);
void* lqRemoveFromBin(void);
void* lqUpdateForNewLocation(void);

#endif
